---

- hosts: all
  become: true
  pre_tasks:

  - name: Ubuntu Update
    tags: always
    apt:
      update_cache: yes
      upgrade: dist

- hosts: Act_15
  become: true
  roles:
    - role: Neutron
    - role: Horizon
    - role: Cinder
