- name: Install Horizon
  apt:
    name: openstack-dashboard
    state: latest
    update_cache: yes

- name: Reload apache2.service
  ansible.builtin.service:
   name: apache2.service
   state: reloaded
